const paths = {
 news:'<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M7 8h4v5H7zM15 8h2m-2 4h2M7 16h10"/>',
 critique:'<path d="M21 11.5a8.4 8.4 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.4 8.4 0 0 1-3.8-.9L3 21l1.9-5.7a8.4 8.4 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.4 8.4 0 0 1 3.8-.9H13a8.5 8.5 0 0 1 8 8v.5Z"/><path d="M8 10h8m-8 4h5"/>',
 fire:'<path d="M12 3s1 5-3 8c0-3-2-4-2-4s-4 4-4 8a9 9 0 0 0 18 0c0-5-5-9-5-9s1 4-1 5c1-5-3-8-3-8Z"/>',
 bookmark:'<path d="m5 21 7-4 7 4V5a2 2 0 0 0-2-2H7a2 2 0 0 0-2 2z"/>',
 user:'<circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/>',
 users:'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8m7-7a4 4 0 0 1 0 7m4 10v-2a4 4 0 0 0-3-3.9"/>',
 search:'<circle cx="10.8" cy="10.8" r="7.2"/><path d="m16 16 5 5"/>',
 bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9m-8 12h4"/>',
 shield:'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6z"/><path d="m8.5 12 2.5 2.5 4.5-5"/>',
 check:'<path d="m5 12 4 4L19 6"/>',
 verified:'<path d="m12 2 3 2.3 3.8.2.7 3.8L22 12l-2.5 3.7-.7 3.8-3.8.2L12 22l-3-2.3-3.8-.2-.7-3.8L2 12l2.5-3.7.7-3.8 3.8-.2Z" fill="currentColor" stroke="none"/><path d="m8 12 2.5 2.5 5.5-5.5" stroke="white" stroke-width="2"/>',
 arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',
 chevron:'<path d="m9 5 7 7-7 7"/>',
 heart:'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/>',
 comment:'<path d="M21 11.5a8.4 8.4 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.4 8.4 0 0 1-3.8-.9L3 21l1.9-5.7a8.4 8.4 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.4 8.4 0 0 1 3.8-.9H13a8.5 8.5 0 0 1 8 8v.5Z"/>',
 share:'<path d="M12 16V3m-5 5 5-5 5 5M5 13v6a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2v-6"/>',
 more:'<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>',
 sliders:'<path d="M4 7h9m4 0h3M4 17h3m4 0h9"/><circle cx="15" cy="7" r="2"/><circle cx="9" cy="17" r="2"/>',
 spark:'<path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5Z"/>',
 sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/>',
 close:'<path d="m6 6 12 12M6 18 18 6"/>',
 link:'<path d="m10 13 4-4m-6 6-2 2a4 4 0 0 1-6-6l5-5a4 4 0 0 1 6 0m2 2 2-2a4 4 0 0 1 6 6l-5 5a4 4 0 0 1-6 0" transform="translate(2 1) scale(.9)"/>',
 document:'<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8zM14 2v6h6M8 13h8m-8 4h6"/>',
 clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
 send:'<path d="m22 2-7 20-4-9L2 9zM22 2 11 13"/>',
 pen:'<path d="m15 4 5 5M4 20l5-1L21 7a3.5 3.5 0 0 0-5-5L4 14z"/>',
 play:'<path d="m9 5 12 7-12 7Z" fill="currentColor" stroke="none"/>',
 volume:'<path d="m11 5-6 4H2v6h3l6 4zm4 3a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14"/>',
 mic:'<rect x="9" y="2" width="6" height="12" rx="3"/><path d="M5 11a7 7 0 0 0 14 0M12 18v4m-4 0h8"/>',
 wave:'<path d="M3 12h2l2-5 4 10 3-7 2 2h5"/>',
 video:'<rect x="2" y="5" width="14" height="14" rx="2"/><path d="m16 10 6-4v12l-6-4"/>',
 building:'<path d="M3 21h18M5 21V4h10v17m0-12h4v12M8 8h4m-4 4h4m-4 4h4"/>',
 globe:'<circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18"/>',
 info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v.1"/>'
};
const icon = (name, cls='') => `<svg class="${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]||paths.news}</svg>`;
const esc = value => String(value).replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const articles = [
 {id:1,publisher:'Horizonte',mark:'h',logo:'',topic:'Sociedade',time:'Há 32 min',image:'urban-park.jpg',category:'CIDADES & FUTURO',title:'Mais árvores, novos caminhos: projeto vai transformar espaços públicos em áreas verdes',summary:'Plano de requalificação prevê parques de bairro, ciclovias e espaços de convivência. A discussão agora é sobre como incluir toda a cidade.',likes:248,comments:42,shares:18,voices:12,claims:['O projeto prevê a criação de três parques de bairro.','O plano inclui 12 quilômetros de novas ciclovias.','A proposta está aberta à consulta pública.'],sources:[['Plano de requalificação urbana','Documento técnico','O plano descreve três parques de bairro e a conexão entre eles por uma rede cicloviária de 12 quilômetros.'],['Portal da consulta pública','Registro primário','O período de participação pública está previsto no cronograma de implantação do projeto.']]},
 {id:2,publisher:'Lume',mark:'l',logo:'lume',topic:'Ciência',time:'Há 1 hora',image:'solar-energy.jpg',category:'CIÊNCIA & ENERGIA',title:'Energia solar compartilhada chega a novos bairros em projeto comunitário',summary:'Iniciativa reúne moradores para dividir a produção de energia limpa. A adesão começa por cinco comunidades do projeto-piloto.',likes:186,comments:28,shares:12,voices:8,claims:['A iniciativa prevê a participação de cinco comunidades.','A produção de energia será compartilhada entre os participantes.','A adesão começa na fase de projeto-piloto.'],sources:[['Plano do projeto comunitário','Documento técnico','A etapa inicial contempla cinco comunidades e define os critérios de participação na produção compartilhada.'],['Comunicado da cooperativa','Fonte primária','O comunicado apresenta o cronograma de adesão e o modelo de divisão da energia entre os participantes.']]},
 {id:3,publisher:'Ponto',mark:'p.',logo:'ponto',topic:'Tecnologia',time:'Há 2 horas',image:null,category:'TECNOLOGIA & SOCIEDADE',title:'Bibliotecas públicas abrem oficinas gratuitas de educação digital',summary:'Da segurança online ao uso responsável da inteligência artificial, a programação quer aproximar diferentes gerações da tecnologia.',likes:94,comments:16,shares:9,voices:6,claims:['As oficinas são gratuitas e abertas ao público.','A programação inclui segurança online e inteligência artificial.'],sources:[['Programação das bibliotecas','Fonte primária','O calendário apresenta as atividades e informa que a inscrição é gratuita.'],['Guia das oficinas','Documento técnico','Os conteúdos incluem segurança na internet e uma introdução ao uso responsável de inteligência artificial.']]}
];
const critiques = [
 {id:1,article:1,name:'Marina Costa',initials:'MC',role:'Arquiteta e urbanista',color:'#e5cdb5',type:'text',text:'Uma cidade mais verde precisa ser uma cidade para todos.',body:'O projeto é um avanço. Mas quem mora longe do centro também vai ter acesso? Quero ver a distribuição desses parques nos bairros, além das imagens bonitas.',likes:86,comments:14,time:'Há 18 min'},
 {id:2,article:2,name:'Rafael Lima',initials:'RL',role:'Educador ambiental',color:'#cbd5b9',type:'video',text:'Energia limpa. Mas acessível para quem?',body:'A conversa sobre energia compartilhada precisa incluir quem mais sente o peso da conta de luz.',likes:123,comments:21,time:'Há 40 min'},
 {id:3,article:3,name:'Luiza Mendes',initials:'LM',role:'Professora e pesquisadora',color:'#e3d4da',type:'text',text:'Educação digital é muito mais do que aprender a usar uma ferramenta.',body:'Entender de onde vem a informação e aprender a fazer boas perguntas são habilidades tão importantes quanto saber usar a tecnologia.',likes:57,comments:9,time:'Há 1 hora'}
];
const articleAudio = {
  1:{duration:'06:42',title:'O contexto por trás do projeto',host:'Redação Horizonte',intro:'Por que a cidade está redesenhando seus espaços públicos?',experts:[{initials:'AC',color:'#d6dfc6',name:'Ana Carvalho',role:'Especialista em cidades',duration:'02:18'},{initials:'MP',color:'#e4d1be',name:'Marcelo Paes',role:'Repórter de urbanismo',duration:'03:06'}]},
  2:{duration:'08:15',title:'Energia para compartilhar',host:'Lume Ciência',intro:'Como funciona o modelo comunitário de energia solar?',experts:[{initials:'BS',color:'#d0d9d0',name:'Bianca Sato',role:'Pesquisadora de energia',duration:'03:12'},{initials:'FN',color:'#eadcc7',name:'Felipe Nunes',role:'Jornalista de ciência',duration:'02:41'}]},
  3:{duration:'05:24',title:'Aprender a navegar no digital',host:'Ponto de encontro',intro:'O que muda quando a biblioteca vira espaço de educação digital?',experts:[{initials:'IR',color:'#d8d2e1',name:'Iara Reis',role:'Pesquisadora de educação',duration:'02:09'},{initials:'GV',color:'#d4e0d0',name:'Gustavo Vale',role:'Editor de tecnologia',duration:'01:54'}]}
};
const communities = [
  {id:'politics',initials:'PB',name:'Política no Brasil',topic:'POLÍTICA',color:'#173f36',accent:'#d9e9b3',members:'18,4 mil',online:'312',description:'Instituições, decisões públicas e o impacto delas na vida real.',publishers:[{name:'República',mark:'R',description:'Política explicada'},{name:'Agência Público',mark:'A',description:'Serviço e cidadania'},{name:'Carta Aberta',mark:'C',description:'Análise e contexto'}],postIds:[1,3]},
  {id:'gossip',initials:'FG',name:'Fofoca de famosos',topic:'CULTURA',color:'#632f4b',accent:'#f4d7e1',members:'9,8 mil',online:'184',description:'Notícias de entretenimento, bastidores e cultura pop com contexto.',publishers:[{name:'Ponto Pop',mark:'P',description:'Cultura e entretenimento'},{name:'Radar 360',mark:'R',description:'Bastidores em foco'},{name:'Cena Aberta',mark:'C',description:'Cinema, música e TV'}],postIds:[2,3]},
  {id:'science',initials:'CT',name:'Ciência no cotidiano',topic:'CIÊNCIA',color:'#214755',accent:'#cae8e0',members:'6,2 mil',online:'97',description:'Evidências, descobertas e perguntas para entender o mundo.',publishers:[{name:'Lume',mark:'l',description:'Ciência para entender'},{name:'Nexo Ciência',mark:'N',description:'Pesquisa e contexto'},{name:'Futuro Agora',mark:'F',description:'Tecnologia responsável'}],postIds:[2,1]}
];
const state = {view:'news',tab:'for-you',topic:'Todos',query:'',saved:new Set(),liked:new Set(),following:new Set(['Horizonte']),critiqueLikes:new Set(),comments:{},ownCritiques:[],critiqueFilter:'Todas',community:'politics',joinedCommunities:new Set(['politics']),communityPublishers:{politics:new Set(['República','Agência Público']),gossip:new Set(['Ponto Pop']),science:new Set(['Lume','Nexo Ciência'])},audioPlaying:null,panel:null,lastFocus:null};
const nav = [{id:'news',icon:'news',label:'Notícias'},{id:'reactions',icon:'critique',label:'Reactions'},{id:'communities',icon:'users',label:'Comunidades'},{id:'popular',icon:'fire',label:'Populares'},{id:'saved',icon:'bookmark',label:'Salvos'},{id:'profile',icon:'user',label:'Meu perfil'}];
let toastTimer;
function toast(message){const el=document.getElementById('toast');el.textContent=message;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),3300)}
function publisherLogo(a){return `<span class="publisher-logo ${a.logo||''}">${a.mark}</span>`}
function avatar(initials,color='',cls=''){return `<span class="avatar ${cls}" ${color?`style="background:${color}"`:''}>${initials}</span>`}
function sidebar(){return `<aside class="sidebar"><button class="brand" data-nav="news" aria-label="TAKTA, início">takta<span class="brand-dot"></span></button><p class="brand-tagline">Fatos conectam. Conversas movem.</p><nav class="navigation" aria-label="Menu principal">${nav.slice(0,3).map(navItem).join('')}<div class="nav-divider"></div><div class="nav-label">SEU ESPAÇO</div>${nav.slice(3).map(navItem).join('')}</nav><div class="sidebar-bottom"><div class="sidebar-manifest">${icon('spark','little-spark')}<p>Fatos primeiro.<br><em>Sua visão depois.</em></p></div><div class="sidebar-foot">Uma conversa com base. <b>FOP</b>${icon('shield','verified-icon')}</div></div></aside>`}
function navItem(n){return `<button class="nav-item ${state.view===n.id?'active':''}" data-nav="${n.id}" ${state.view===n.id?'aria-current="page"':''}>${icon(n.icon)}<span>${n.label}</span>${n.id==='saved'&&state.saved.size?`<span class="nav-count">${state.saved.size}</span>`:''}</button>`}
function header(){return `<header class="topbar"><div class="topbar-title"><span class="desktop-title">${nav.find(n=>n.id===state.view)?.label||'Notícias'}</span><span class="mobile-brand">takta</span><span class="topbar-divider"></span><span class="topbar-note">Seu olhar faz parte.</span></div><div class="header-tools"><label class="search-wrap" id="search-wrap">${icon('search')}<input id="global-search" type="search" placeholder="O que você quer explorar?" aria-label="Buscar notícias" value="${esc(state.query)}"/><kbd>/</kbd></label><button class="icon-button" data-action="notifications" aria-label="Notificações">${icon('bell')}<span class="notification-dot"></span></button><button class="icon-button" data-nav="profile" aria-label="Meu perfil">${avatar('CH','','me')}</button></div></header>`}
function rightColumn(){return `<aside class="right-column"><section class="trending-section"><h2 class="section-kicker">Em pauta ${icon('fire')}</h2><p class="section-caption">CONVERSAS QUE IMPORTAM</p>${[['Sociedade','O futuro das nossas cidades','128 pessoas conversando'],['Ciência','Energia que se compartilha','96 pessoas conversando'],['Tecnologia','IA no nosso dia a dia','74 pessoas conversando']].map((t,i)=>`<button class="trending-row" data-topic="${t[0]}"><span class="trending-number">0${i+1}</span><span><span class="trend-topic">${t[0].toUpperCase()}</span><span class="trend-title">${t[1]}</span><span class="trend-count">${t[2]}</span></span></button>`).join('')}</section><section class="publishers-section"><h2 class="section-kicker">Outros olhares ${icon('globe')}</h2>${[articles[2],articles[1]].map(a=>`<div class="suggestion">${publisherLogo(a)}<div class="suggestion-info"><strong>${a.publisher} ${icon('verified','verified-icon')}</strong><small>${a.id===3?'Tecnologia e cotidiano':'Ciência para entender o mundo'}</small></div><button class="follow-button ${state.following.has(a.publisher)?'following':''}" data-follow="${a.publisher}">${state.following.has(a.publisher)?'Seguindo':'Seguir'}</button></div>`).join('')}</section><section class="fop-intro"><div class="fop-wordmark">${icon('shield')} FOP</div><h3>Boas conversas<br>começam com fatos.</h3><p>Antes de chegar até você, cada notícia passa por uma análise de evidências.</p><button data-action="how">Conheça a FOP ${icon('arrow')}</button></section><footer class="right-footer"><div class="demo-label">${icon('info')} Protótipo visual · conteúdo fictício</div><span>TAKTA © 2026 · Facts first. Your take next.</span></footer></aside>`}
function greeting(){const titles={news:['O mundo acontece.','A conversa começa aqui.','Notícias com base. Espaço para o seu ponto de vista.'],reactions:['Uma notícia.','Muitos pontos de vista.','Reações em vídeo para descobrir como outras pessoas estão lendo o mundo.'],communities:['Encontre a sua','comunidade.','Converse sobre os temas que importam, seguindo os portais escolhidos por cada grupo.'],popular:['O que move','a conversa de hoje.','Notícias e perspectivas que estão fazendo a comunidade pensar.'],saved:['Boas leituras,','no seu tempo.','Seu espaço para voltar às notícias que merecem outro olhar.'],profile:['Seu espaço.','Sua perspectiva.','As conversas que você acompanha e as ideias que compartilha.']};const t=titles[state.view]||titles.news;return `<section class="greeting"><div class="greeting-meta">${icon('sun')} QUINTA-FEIRA, 10 DE SETEMBRO</div><h1>${t[0]}<br><span>${t[1]}</span></h1><p>${t[2]}</p><div class="mobile-demo">Protótipo visual · conteúdo fictício</div></section>`}
function feedControls(){return `<div class="feed-tabs" role="tablist" aria-label="Origem das notícias"><button class="feed-tab ${state.tab==='for-you'?'active':''}" role="tab" aria-selected="${state.tab==='for-you'}" data-tab="for-you">Para você</button><button class="feed-tab ${state.tab==='following'?'active':''}" role="tab" aria-selected="${state.tab==='following'}" data-tab="following">Seguindo</button><button class="feed-settings" data-action="feed-info" aria-label="Sobre a seleção do feed">${icon('sliders')}</button></div><div class="topic-list" aria-label="Filtrar por assunto">${['Todos','Sociedade','Tecnologia','Ciência','Cultura','Planeta'].map(t=>`<button class="topic ${state.topic===t?'active':''}" data-topic="${t}" aria-pressed="${state.topic===t}">${t}</button>`).join('')}</div>`}
function evidenceStrip(a){return `<div class="evidence-strip"><span class="evidence-state">${icon('shield')} Verificada pela <b>FOP</b><span class="dot-separator">·</span><span class="evidence-detail">${a.sources.length} fontes</span></span><button class="evidence-link" data-evidence="${a.id}">Ver evidências ${icon('chevron')}</button></div>`}
function newsCard(a,rank=false){return `<article class="news-card" id="news-${a.id}"><div class="card-publisher">${publisherLogo(a)}<div class="publisher-details"><span class="publisher-name">${a.publisher} ${icon('verified','verified-icon')}</span><span class="publisher-meta">${a.time} · ${a.topic}</span></div>${rank?`<span class="rank-pill">${icon('fire')} Em alta</span>`:''}<button class="more-button icon-button" data-more="${a.id}" aria-label="Opções da notícia">${icon('more')}</button></div>${a.image?`<div class="card-photo-wrap"><img class="card-photo" src="./assets/${a.image}" alt="${a.id===1?'Vista aérea de um grande parque arborizado cercado por edifícios':'Painéis solares em uma área aberta sob o céu azul'}" ${a.id!==1?'loading="lazy"':''}/><span class="photo-category">${a.category}</span><span class="photo-credit">Imagem ilustrativa</span></div>`:`<div class="text-category">${a.category}</div>`}<div class="card-content"><button class="headline-button" data-article="${a.id}"><h2>${a.title}</h2></button><p class="card-summary">${a.summary}</p>${audioModule(a,true)}${evidenceStrip(a)}<div class="card-actions"><button class="card-action ${state.liked.has(a.id)?'selected':''}" data-like="${a.id}" aria-label="Curtir notícia" aria-pressed="${state.liked.has(a.id)}">${icon('heart')} <span>${a.likes+(state.liked.has(a.id)?1:0)}</span></button><button class="card-action" data-comments="${a.id}" aria-label="Ver comentários">${icon('comment')} <span>${a.comments+(state.comments[a.id]?.length||0)}</span></button><button class="card-action" data-share="${a.id}" aria-label="Compartilhar notícia">${icon('share')} <span>${a.shares}</span></button><button class="card-action ${state.saved.has(a.id)?'selected':''}" data-save="${a.id}" aria-label="${state.saved.has(a.id)?'Remover dos salvos':'Salvar notícia'}" aria-pressed="${state.saved.has(a.id)}">${icon('bookmark')}</button></div></div><div class="mini-discussion"><div class="discussion-caption"><div class="avatar-stack">${avatar('MC','#e5cdb5')}${avatar('RL','#cbd5b9')}${avatar('LM','#e3d4da')}</div><span><strong>${a.voices} olhares</strong> sobre esta notícia</span></div><button class="discussion-button" data-view-critiques="${a.id}">Ver reactions ${icon('arrow')}</button></div></article>`}
function empty(title,text,action='news',button='Explorar notícias'){return `<div class="empty-state">${icon('bookmark')}<h2>${title}</h2><p>${text}</p><button class="button-secondary" data-nav="${action}">${button} ${icon('arrow')}</button></div>`}
function feed(){let list=articles.filter(a=>(state.topic==='Todos'||a.topic===state.topic||(state.topic==='Planeta'&&a.id===2))&&(state.tab!=='following'||state.following.has(a.publisher))&&(!state.query||`${a.title} ${a.summary} ${a.publisher} ${a.topic}`.toLocaleLowerCase('pt-BR').includes(state.query.toLocaleLowerCase('pt-BR'))));return `${greeting()}${feedControls()}<div id="feed-results">${list.map(a=>newsCard(a)).join('')||empty('Um assunto para a próxima conversa','Não há notícias demonstrativas nesta seleção. Experimente outro assunto.','news','Limpar filtros')}</div>`}
function render(){const previousScroll=window.scrollY;document.getElementById('app').innerHTML=`<div class="app-shell">${sidebar()}<div class="workspace">${header()}<div class="content-grid"><main class="main-column" id="main-content">${state.view==='news'?feed():renderView()}</main>${rightColumn()}</div></div><nav class="mobile-nav" aria-label="Navegação móvel">${nav.map(n=>`<button class="mobile-item ${state.view===n.id?'active':''}" data-nav="${n.id}" ${state.view===n.id?'aria-current="page"':''}>${icon(n.icon)}<span>${n.id==='profile'?'Perfil':n.label}</span></button>`).join('')}</nav></div>`;window.scrollTo(0,previousScroll)}
function navigate(view){closePanel();state.view=view;state.query='';state.topic='Todos';state.tab='for-you';state.articleFilter=null;state.critiqueFilter='Todas';render();window.scrollTo({top:0,behavior:'instant'})}
function openPanel(title,body,footer='',modal=false){if(!state.panel)state.lastFocus=document.activeElement;state.panel=title;document.getElementById('overlay-root').innerHTML=`<div class="overlay-backdrop ${modal?'modal-layout':''}"><section class="detail-panel" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><header class="panel-header">${title==='FOP'?`<h2 class="fop-wordmark" id="dialog-title">${icon('shield')} FOP <span class="fop-submark">Fact On Publication</span></h2>`:`<h2 id="dialog-title">${title}</h2>`}<button class="icon-button" data-action="close" aria-label="Fechar painel">${icon('close')}</button></header><div class="panel-body">${body}</div>${footer?`<footer class="panel-footer">${footer}</footer>`:''}</section></div>`;document.body.style.overflow='hidden';document.querySelector('[data-action="close"]').focus()}
function closePanel(){document.getElementById('overlay-root').innerHTML='';document.body.style.overflow='';state.panel=null;if(state.lastFocus?.isConnected)state.lastFocus.focus()}
function showEvidence(id){const a=articles.find(a=>a.id===id);openPanel('FOP',`<div class="eyebrow">POR TRÁS DA NOTÍCIA</div><h3 class="panel-headline">${a.title}</h3><div class="status-card"><div class="status-title">${icon('shield')} Sustentada pelas evidências</div><p>As fontes deste exemplo sustentam as afirmações analisadas. A interpretação da notícia continua com você.</p><div class="status-meta"><span>${icon('check')} Confiança alta</span><span>${icon('document')} ${a.sources.length} fontes</span><span>${icon('clock')} Análise demonstrativa</span></div></div><h3 class="panel-subtitle">O que foi analisado</h3><div class="claim-list">${a.claims.map(c=>`<div class="claim-item">${icon('check')}<span>${c}</span></div>`).join('')}</div><h3 class="panel-subtitle">Evidências que sustentam</h3>${a.sources.map((s,i)=>`<article class="source-card"><div class="source-top"><span class="source-icon">${icon(i?'globe':'document')}</span>${s[0]}<small>Sustenta</small></div><p>“${s[2]}”</p><footer>${s[1]} · fonte e trecho fictícios</footer></article>`).join('')}<p class="demo-note">Este é um exemplo visual. A notícia, as fontes e o resultado foram criados para demonstrar a experiência. Nenhuma verificação real foi executada.</p>`,`<button class="button-secondary full-width" data-action="how">Como a FOP chega a uma análise? ${icon('arrow')}</button>`)}
function showArticle(id){const a=articles.find(a=>a.id===id);openPanel('A notícia',`<div class="card-publisher article-publisher">${publisherLogo(a)}<div><span class="publisher-name">${a.publisher}${icon('verified','verified-icon')}</span><span class="publisher-meta">${a.time} · Leitura de 3 min</span></div></div><h3 class="panel-headline">${a.title}</h3>${evidenceStrip(a)}<div class="article-reading">${a.image?`<img src="./assets/${a.image}" alt="Fotografia ilustrativa da notícia"/>`:''}<p>${a.summary}</p>${audioModule(a,false)}<p>${id===1?'A proposta coloca a qualidade de vida no centro do planejamento urbano. O projeto demonstrativo combina a criação de três parques de bairro com 12 quilômetros de ciclovias, conectando espaços de lazer a trajetos do dia a dia.':id===2?'O projeto demonstrativo apresenta um modelo de participação coletiva. Em vez de cada residência instalar um sistema próprio, os participantes compartilham a produção de uma estrutura comunitária.':'A programação demonstrativa aproxima moradores de diferentes idades da tecnologia, com encontros sobre segurança online, pesquisa de informação e inteligência artificial.'}</p><h3>O que está em discussão</h3><p>O acesso, a participação da comunidade e os impactos no cotidiano são pontos centrais do debate. Os documentos apresentados explicam a proposta, mas suas consequências ainda permitem diferentes leituras.</p><p class="article-quote">Os fatos são o ponto de partida. A conversa sobre o que eles significam pertence a todos.</p><p>A TAKTA reúne essas perspectivas em um mesmo lugar, sempre conectadas à notícia que iniciou a discussão.</p></div><p class="demo-note">Notícia fictícia para demonstração do protótipo. Fotografias meramente ilustrativas.</p>`,`<button class="button-secondary" data-comments="${id}">${icon('comment')} Comentários</button><button class="button-primary" data-compose="${id}">${icon('pen')} Minha reaction</button>`)}
function showComments(id){const a=articles.find(a=>a.id===id);const examples=[{name:'Marina Costa',initials:'MC',color:'#e5cdb5',text:id===1?'Gostei de ver a consulta pública entre as evidências. Quero entender como os bairros vão participar dessa decisão.':'O ponto principal para mim é saber como as pessoas vão participar. A proposta abre uma boa conversa.',likes:18},{name:'João Pedro',initials:'JP',color:'#c8d7dc',text:'A notícia traz a proposta, mas acompanhar a execução vai ser tão importante quanto o anúncio.',likes:12}];openPanel('A conversa',`<div class="eyebrow">SOBRE ESTA NOTÍCIA</div><h3 class="panel-headline">${a.title}</h3><div class="comment-section-title">Diferentes olhares, uma conversa.</div>${[...examples,...(state.comments[id]||[])].map(c=>`<article class="comment-item">${avatar(c.initials,c.color)}<div class="comment-content"><div class="comment-name">${esc(c.name)}<span>${c.name==='Charles'?'Agora':'Há 15 min'}</span></div><p>${esc(c.text)}</p><div class="comment-actions"><button data-action="comment-like" aria-label="Curtir comentário">${icon('heart')} <span>${c.likes||0}</span></button><button data-reply="${esc(c.name)}">Responder</button></div></div></article>`).join('')}<p class="compose-hint">Discordar faz parte. Respeitar também.</p>`,`<form class="comment-composer" data-comment-form="${id}"><input name="comment" maxlength="1500" required placeholder="Qual é o seu ponto de vista?" aria-label="Escrever comentário"/><button class="send-button" aria-label="Enviar comentário">${icon('send')}</button></form>`)}
function showCompose(id){const a=articles.find(a=>a.id===id);openPanel('Seu ponto de vista',`<div class="eyebrow">TODA CRÍTICA COMEÇA COM UMA NOTÍCIA</div><h3 class="panel-headline">O que essa notícia faz você pensar?</h3><div class="linked-news">${icon('link')}<span><small>REAGINDO À NOTÍCIA · ${a.publisher.toUpperCase()}</small>${a.title}</span></div><div class="format-choice"><button class="active" type="button">${icon('pen')} Em texto</button><button data-action="video-demo" type="button">${icon('video')} Em vídeo</button></div><form id="critique-form" data-critique-form="${id}"><label class="compose-label" for="critique-text">Sua perspectiva</label><textarea id="critique-text" class="compose-textarea" name="critique" placeholder="Concorde, questione, traga outro ângulo..." maxlength="2000" required></textarea><p class="compose-hint">Traga argumentos e respeite outros pontos de vista. Sua crítica sempre ficará vinculada à notícia original.</p><p class="demo-note">A publicação será simulada apenas nesta sessão do protótipo.</p></form>`,`<button class="button-secondary" data-action="close">Cancelar</button><button class="button-primary" form="critique-form" type="submit">Publicar crítica ${icon('arrow')}</button>`)}
function showHow(){openPanel('FOP',`<div class="eyebrow">FATOS PRIMEIRO. SUA VISÃO DEPOIS.</div><h3 class="how-title">Uma base confiável.<br><em>Mil formas de pensar.</em></h3>${[['A notícia chega','Um veículo com identidade verificada envia uma notícia antes de publicá-la.'],['As evidências entram em cena','A FOP identifica afirmações e busca fontes relevantes para comparar o que elas dizem.'],['A análise fica à vista','Você pode consultar o que sustenta, contradiz ou ainda não permite concluir sobre uma afirmação.']].map((s,i)=>`<div class="how-step"><div class="how-number">${i+1}</div><div><h3>${s[0]}</h3><p>${s[1]}</p></div></div>`).join('')}<div class="state-legend"><div class="state-chip support">Sustentada</div><div class="state-chip refute">Refutada</div><div class="state-chip wait">Evidências insuficientes</div><div class="state-chip conflict">Evidências conflitantes</div></div><p class="demo-note">Não encontrar evidências não significa que uma afirmação seja falsa. A FOP apoia a avaliação factual; opiniões e interpretações continuam com a comunidade.<br><br>Neste protótipo, todas as análises são demonstrativas.</p>`,`<button class="button-primary full-width" data-action="close">Entendi. Vamos à conversa. ${icon('arrow')}</button>`,true)}
document.addEventListener('click',async event=>{
 const b=event.target.closest('button');
 if(event.target.classList.contains('overlay-backdrop'))return closePanel();
 if(event.target.closest('#search-wrap')&&window.innerWidth<=600){document.getElementById('search-wrap').classList.add('search-open');document.getElementById('global-search').focus()}
 if(!b)return;
 const d=b.dataset;
 if(d.nav)return navigate(d.nav);
 if(d.tab){state.tab=d.tab;render();return}
 if(d.topic){state.view='news';state.topic=d.topic;state.articleFilter=null;render();window.scrollTo({top:0,behavior:'smooth'});return}
 if(d.community){state.view='communities';state.community=d.community;render();window.scrollTo({top:0,behavior:'smooth'});return}
 if(d.communityJoin){state.joinedCommunities.has(d.communityJoin)?state.joinedCommunities.delete(d.communityJoin):state.joinedCommunities.add(d.communityJoin);render();toast(state.joinedCommunities.has(d.communityJoin)?'Você entrou na comunidade.':'Você saiu da comunidade.');return}
 if(d.communityPublisher){const [communityId,publisherName]=d.communityPublisher.split('|');const selected=state.communityPublishers[communityId]??(state.communityPublishers[communityId]=new Set());selected.has(publisherName)?selected.delete(publisherName):selected.add(publisherName);render();toast(selected.has(publisherName)?`${publisherName} adicionado à timeline.`:`${publisherName} removido da timeline.`);return}
 if(d.evidence)return showEvidence(Number(d.evidence));
 if(d.article)return showArticle(Number(d.article));
 if(d.comments)return showComments(Number(d.comments));
 if(d.compose)return showCompose(Number(d.compose));
 if(d.audioPlay){const id=Number(d.audioPlay);state.audioPlaying=state.audioPlaying===id?null:id;render();toast(state.audioPlaying===id?'Podcast demonstrativo iniciado.':'Podcast pausado.');return}
 if(d.expertAudio){const [articleId,index]=d.expertAudio.split('|');const audio=articleAudio[Number(articleId)];const expert=audio?.experts[Number(index)];toast(expert?`Comentário de ${expert.name} iniciado.`:'Comentário em áudio demonstrativo.');return}
 if(d.audioInfo){openPanel('Áudio da notícia',`<div class="eyebrow">PODCAST E DEBATE</div><h3 class="panel-headline">${articleAudio[Number(d.audioInfo)]?.title||'Áudio editorial'}</h3><p class="article-reading">O publisher pode publicar um episódio curto com contexto e, logo abaixo, abrir espaço para comentários de especialistas em jornalismo, ciência ou no tema da notícia.</p><p class="demo-note">O player e os comentários desta tela são demonstrativos; nenhum arquivo de áudio é reproduzido.</p>`,`<button class="button-primary full-width" data-action="close">Voltar à notícia</button>`,true);return}
 if(d.like){const id=Number(d.like);state.liked.has(id)?state.liked.delete(id):state.liked.add(id);const a=articles.find(a=>a.id===id);b.classList.toggle('selected',state.liked.has(id));b.setAttribute('aria-pressed',state.liked.has(id));b.querySelector('span').textContent=a.likes+(state.liked.has(id)?1:0);return}
 if(d.save){const id=Number(d.save);state.saved.has(id)?state.saved.delete(id):state.saved.add(id);render();toast(state.saved.has(id)?'Notícia salva no seu espaço.':'Notícia removida dos salvos.');return}
 if(d.follow){state.following.has(d.follow)?state.following.delete(d.follow):state.following.add(d.follow);render();return}
 if(d.share){const a=articles.find(a=>a.id===Number(d.share));openPanel('Compartilhar notícia',`<h3 class="panel-headline">Leve essa conversa adiante.</h3><div class="linked-news">${icon('news')}<span>${a.title}</span></div><p class="compose-hint">Compartilhamento demonstrativo. Você pode copiar o título para apresentar esta ideia.</p>`,`<button class="button-primary full-width" data-copy="${a.id}">${icon('link')} Copiar título da notícia</button>`,true);return}
 if(d.copy){try{await navigator.clipboard.writeText('[Exemplo fictício TAKTA] '+articles.find(a=>a.id===Number(d.copy)).title);toast('Título copiado.')}catch{toast('A cópia não está disponível neste navegador.')}return}
 if(d.more){const a=articles.find(a=>a.id===Number(d.more));openPanel('Sobre esta publicação',`<div class="card-publisher">${publisherLogo(a)}<div><span class="publisher-name">${a.publisher} ${icon('verified','verified-icon')}</span><span class="publisher-meta">Veículo fictício · identidade demonstrativa</span></div></div><p class="compose-hint">A identificação do veículo indica quem publica. A FOP apresenta, separadamente, as evidências da notícia.</p>`,`<button class="button-secondary full-width" data-evidence="${a.id}">Consultar evidências ${icon('arrow')}</button>`,true);return}
 if(d.viewCritiques){state.view='reactions';state.articleFilter=Number(d.viewCritiques);render();window.scrollTo({top:0,behavior:'smooth'});return}
 if(d.critiqueFilter){state.critiqueFilter=d.critiqueFilter;render();return}
 if(d.critiqueLike){const id=d.critiqueLike;state.critiqueLikes.has(id)?state.critiqueLikes.delete(id):state.critiqueLikes.add(id);render();return}
 if(d.play){showVideoDemo(Number(d.play));return}
 if(d.reply){const input=document.querySelector('.comment-composer input');input.value=`@${d.reply} `;input.focus();return}
 if(d.action==='close')return closePanel();
 if(d.action==='video-compose')return videoCompose(Number(d.videoArticle)||state.articleFilter||1);
 if(d.action==='start-record'){toast('A câmera será conectada em uma próxima etapa do protótipo.');return;}
 if(d.action==='create-community'){openPanel('Criar comunidade',`<div class="eyebrow">UM ESPAÇO PARA UMA CONVERSA</div><h3 class="panel-headline">Que tema você quer reunir?</h3><div class="community-create-preview">${icon('users')}<span><strong>Nome da comunidade</strong><small>Ex.: Política no Brasil</small></span></div><div class="community-create-preview">${icon('globe')}<span><strong>Portais da timeline</strong><small>O admin escolhe quais veículos entram no feed.</small></span></div><p class="demo-note">A criação de comunidades será simulada em uma próxima etapa. Esta tela mostra o fluxo previsto.</p>`,`<button class="button-secondary" data-action="close">Cancelar</button><button class="button-primary" data-action="community-create-demo">Criar espaço ${icon('arrow')}</button>`,true);return}
 if(d.action==='community-create-demo'){closePanel();toast('A criação de comunidades será conectada em uma próxima etapa.');return}
 if(d.action==='community-admin'){document.querySelector('.community-admin')?.scrollIntoView({behavior:'smooth',block:'center'});toast('O admin controla os portais nesta coluna.');return}
 if(d.action==='community-about'){const c=communities.find(item=>item.id===state.community)||communities[0];openPanel('Sobre a comunidade',`<div class="community-about-mark" style="background:${c.color};color:${c.accent}">${c.initials}</div><h3 class="panel-headline">${c.name}</h3><p class="article-reading">${c.description}</p><div class="community-about-stats"><span><strong>${c.members}</strong>membros</span><span><strong>${c.online}</strong>online agora</span></div><p class="demo-note">Comunidades são espaços temáticos. O admin escolhe portais para formar a timeline; as pessoas entram para ler, ouvir e reagir.</p>`,`<button class="button-primary full-width" data-action="close">Voltar à timeline</button>`,true);return}
 if(d.action==='community-add-publisher'){toast('Busca de portais será conectada em uma próxima etapa.');return}
 if(d.action==='video-info'){openPanel('Críticas em vídeo',`<h3 class="panel-headline">O seu ponto de vista também pode ganhar movimento.</h3><p class="article-reading">Grave uma reação curta, escolha a notícia que inspirou a conversa e publique seu olhar para a comunidade. Cada vídeo permanece ligado à notícia original.</p><p class="demo-note">Neste protótipo, os vídeos são apresentados como prévias visuais e nenhuma câmera é ativada.</p>`,`<button class="button-primary full-width" data-action="video-compose">Conhecer a tela de gravação ${icon('arrow')}</button>`,true);return}
 if(d.action==='how')return showHow();
 if(d.action==='clear-article'){state.articleFilter=null;render();return}
 if(d.action==='comment-like'){const selected=b.getAttribute('aria-pressed')==='true';const el=b.querySelector('span');el.textContent=Number(el.textContent)+(selected?-1:1);b.setAttribute('aria-pressed',!selected);b.style.color=selected?'':'var(--green)';return}
 if(d.action==='video-demo'){toast('Envio de vídeo será conectado em uma próxima etapa. Experimente a crítica em texto.');return}
 if(d.action==='feed-info'){openPanel('Seu feed, outros olhares',`<h3 class="panel-headline">Um ponto de partida para boas conversas.</h3><p class="article-reading">Em “Para você”, explore as notícias demonstrativas de todos os veículos. Em “Seguindo”, veja apenas os veículos que você escolheu acompanhar.</p><p class="demo-note">A seleção deste protótipo é fixa. Não há algoritmo de recomendação em execução.</p>`,`<button class="button-primary full-width" data-action="close">Continuar explorando</button>`,true);return}
 if(d.action==='notifications'){openPanel('Notificações',`<div class="notification-item">${avatar('MC','#e5cdb5')}<div><strong>A conversa continua</strong><p>Marina Costa trouxe uma nova perspectiva sobre os espaços verdes da cidade.</p><button class="text-link" data-comments="1">Ir para a conversa ${icon('arrow')}</button></div></div><p class="demo-note">Notificação demonstrativa.</p>`,'',true);return}
});
document.addEventListener('input',event=>{if(event.target.id==='global-search'){state.query=event.target.value;state.view='news';state.topic='Todos';document.getElementById('main-content').innerHTML=feed();document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav==='news'));document.querySelector('.desktop-title').textContent='Notícias'}});
document.addEventListener('submit',event=>{if(event.target.dataset.commentForm){event.preventDefault();const id=Number(event.target.dataset.commentForm);const input=event.target.elements.comment;const text=input.value.trim();if(!text)return;(state.comments[id]??=[]).push({name:'Charles',initials:'CH',color:'#eadfd3',text,likes:0});showComments(id);render();toast('Comentário adicionado à demonstração.')}if(event.target.dataset.critiqueForm){event.preventDefault();const text=event.target.elements.critique.value.trim();if(!text)return;const id=Number(event.target.dataset.critiqueForm);state.ownCritiques.unshift({id:`own-${Date.now()}`,article:id,name:'Charles',initials:'CH',role:'Seu ponto de vista',color:'#eadfd3',type:'text',text:text.length>95?text.slice(0,95)+'…':text,body:text.length>95?text:'',likes:0,comments:0,time:'Agora'});closePanel();state.view='reactions';state.critiqueFilter='Todas';state.articleFilter=null;render();window.scrollTo({top:0,behavior:'smooth'});toast('Sua reaction foi adicionada à demonstração.')}});
document.addEventListener('keydown',event=>{if(event.key==='Escape')closePanel();if(event.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)&&!state.panel){event.preventDefault();document.getElementById('search-wrap').classList.add('search-open');document.getElementById('global-search').focus()}if(event.key==='Tab'&&state.panel){const elements=[...document.querySelectorAll('.detail-panel button:not([disabled]), .detail-panel input, .detail-panel textarea, .detail-panel a[href]')];const first=elements[0],last=elements.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}}});
render();
